### ISSUE TITLE
Doesnt work no instagram py

### ISSUE THREAD

**Issue by rodt974** [JuanEGamerYT/ighack#1]
python: can't open file '/root/ighack/instagram-py': [Errno 2] No such file or directory

**Comment by JuanEGamerYT** [comment]
Thanks for letting me know, I fixed it, let me know if it's still the same

Gracias por avisarme, lo arreglé, hágamelo saber si sigue siendo el mismo.

**Comment by JuanEGamerYT** [comment]
Run setup.sh again

Vuelve a ejecutar setup.sh


(Primero actualiza el programa), update.sh

**Comment by rodt974** [comment]
Still the same

**Comment by rodt974** [comment]
now i have this problem : fatal error:: Tor configuration invalid or server down :: [Errno 111] Connection refused

**Comment by JuanEGamerYT** [comment]
It's because of a tor problem and I'll fix that. Use setup.sh, it was configured to fix such a problem

**Comment by JuanEGamerYT** [comment]
Later I release a new update. For now I'm in school bro

**Comment by JuanEGamerYT** [comment]
https://github.com/deathsec/instagram-py/issues/8#issuecomment-656743574 Fix it with this, it helped me, it's because of port control, I'll learn soon and I'll make it happen automatically with setup.sh.

**Comment by JuanEGamerYT** [comment]
Solved case
